"""
Positronic - Block and Transaction Validation Rules
Validates blocks and transactions before they are added to the chain.
All transactions are fully traceable - no privacy/anonymous transfers.
"""

from typing import Optional, List
from dataclasses import dataclass

from positronic.core.block import Block, BlockHeader
from positronic.core.transaction import Transaction, TxType, TxStatus
from positronic.core.state import StateManager
from positronic.crypto.address import address_from_pubkey
from positronic.constants import (
    BLOCK_GAS_LIMIT,
    MAX_BLOCK_SIZE,
    CHAIN_ID,
    BLOCK_HEADER_VERSION,
    TX_BASE_GAS,
    MIN_GAS_PRICE,
    MIN_BLOCK_GAS_LIMIT,
    MAX_BLOCK_GAS_LIMIT,
    GAS_LIMIT_ADJUSTMENT_FACTOR,
    TOTAL_SUPPLY,
    GENESIS_HASH,
    TESTNET_GENESIS_HASH,
)


@dataclass
class ValidationResult:
    """Result of a validation check."""
    valid: bool
    error: str = ""


class TransactionValidator:
    """Validates individual transactions."""

    # Transaction types that are always system-generated and need no
    # signature, gas, nonce, or balance checks.
    SYSTEM_TX_TYPES = frozenset({TxType.REWARD, TxType.AI_TREASURY, TxType.GAME_REWARD})

    def __init__(self, immune_system=None):
        self._immune_system = immune_system

    @staticmethod
    def is_system_tx(tx: Transaction) -> bool:
        """Return True if *tx* is a system-generated transaction.

        System TXs are either one of the known system types (REWARD,
        AI_TREASURY, GAME_REWARD) **or** any TX created via
        ``_create_system_tx`` / ``_pending_system_txs`` which is marked by
        having an empty signature **and** zero gas parameters.
        """
        if tx.tx_type in TransactionValidator.SYSTEM_TX_TYPES:
            return True
        # Heuristic: empty signature + gas_price==0 + gas_limit==0 means the
        # TX was injected as a system record (admin transfer, RPC stake, etc.)
        if tx.signature == b"" and tx.gas_price == 0 and tx.gas_limit == 0:
            return True
        return False

    def validate(
        self,
        tx: Transaction,
        state: StateManager,
        current_height: int = 0,
    ) -> ValidationResult:
        """Run all validation checks on a transaction."""
        # System TXs bypass normal validation — they are generated by the
        # node itself and only need basic structural sanity.
        if self.is_system_tx(tx):
            return ValidationResult(valid=True)

        checks = [
            self._check_blacklist(tx),
            self._check_signature(tx),
            self._check_chain_id(tx),
            self._check_value(tx),
            self._check_gas_limit(tx),
            self._check_gas_price(tx),
            self._check_nonce(tx, state),
            self._check_balance(tx, state),
            self._check_data_size(tx),
        ]

        for result in checks:
            if not result.valid:
                return result

        return ValidationResult(valid=True)

    def _check_blacklist(self, tx: Transaction) -> ValidationResult:
        """Check if sender is blocked by the immune system."""
        if self.is_system_tx(tx):
            return ValidationResult(valid=True)
        if self._immune_system is None:
            return ValidationResult(valid=True)
        sender_addr = address_from_pubkey(tx.sender) if tx.sender else b""
        if self._immune_system.is_address_blocked(sender_addr):
            return ValidationResult(
                valid=False,
                error=f"Sender {sender_addr.hex()[:16]}... is blocked by immune system",
            )
        return ValidationResult(valid=True)

    def _check_signature(self, tx: Transaction) -> ValidationResult:
        """Verify transaction signature."""
        if self.is_system_tx(tx):
            return ValidationResult(valid=True)

        if not tx.verify_signature():
            return ValidationResult(valid=False, error="Invalid signature")
        return ValidationResult(valid=True)

    def _check_chain_id(self, tx: Transaction) -> ValidationResult:
        """Verify chain ID matches."""
        if tx.chain_id != CHAIN_ID:
            return ValidationResult(
                valid=False,
                error=f"Wrong chain ID: {tx.chain_id} (expected {CHAIN_ID})",
            )
        return ValidationResult(valid=True)

    def _check_value(self, tx: Transaction) -> ValidationResult:
        """Check transaction value is within valid range."""
        if tx.value < 0:
            return ValidationResult(
                valid=False, error="Negative transaction value",
            )
        if tx.value > TOTAL_SUPPLY:
            return ValidationResult(
                valid=False,
                error=f"Transaction value {tx.value} exceeds total supply",
            )
        return ValidationResult(valid=True)

    def _check_gas_limit(self, tx: Transaction) -> ValidationResult:
        """Check gas limit is sufficient."""
        if self.is_system_tx(tx):
            return ValidationResult(valid=True)
        if tx.gas_limit < tx.intrinsic_gas:
            return ValidationResult(
                valid=False,
                error=f"Gas limit {tx.gas_limit} below intrinsic gas {tx.intrinsic_gas}",
            )
        if tx.gas_limit > BLOCK_GAS_LIMIT:
            return ValidationResult(
                valid=False,
                error=f"Gas limit {tx.gas_limit} exceeds block gas limit",
            )
        return ValidationResult(valid=True)

    def _check_gas_price(self, tx: Transaction) -> ValidationResult:
        """Check gas price meets minimum requirement."""
        if self.is_system_tx(tx):
            return ValidationResult(valid=True)
        if tx.gas_price < MIN_GAS_PRICE:
            return ValidationResult(
                valid=False,
                error=f"Gas price {tx.gas_price} below minimum {MIN_GAS_PRICE}",
            )
        return ValidationResult(valid=True)

    def _check_nonce(self, tx: Transaction, state: StateManager) -> ValidationResult:
        """Check sender nonce matches expected value."""
        if self.is_system_tx(tx):
            return ValidationResult(valid=True)

        sender_addr = address_from_pubkey(tx.sender)
        expected_nonce = state.get_nonce(sender_addr)

        if tx.nonce != expected_nonce:
            return ValidationResult(
                valid=False,
                error=f"Invalid nonce: {tx.nonce} (expected {expected_nonce})",
            )
        return ValidationResult(valid=True)

    def _check_balance(self, tx: Transaction, state: StateManager) -> ValidationResult:
        """Check sender has sufficient effective balance (excludes staked funds)."""
        if self.is_system_tx(tx):
            return ValidationResult(valid=True)

        sender_addr = address_from_pubkey(tx.sender)
        acc = state.get_account(sender_addr)
        available = acc.effective_balance

        if available < tx.total_cost:
            return ValidationResult(
                valid=False,
                error=f"Insufficient balance: {available} < {tx.total_cost} "
                      f"(staked: {acc.staked_amount})",
            )
        return ValidationResult(valid=True)

    def _check_data_size(self, tx: Transaction) -> ValidationResult:
        """Check transaction data isn't too large."""
        if len(tx.data) > 128 * 1024:  # 128 KB max
            return ValidationResult(
                valid=False,
                error=f"Transaction data too large: {len(tx.data)} bytes",
            )
        return ValidationResult(valid=True)


class BlockValidator:
    """Validates blocks."""

    def __init__(self, *, network_type: str = "main"):
        self.tx_validator = TransactionValidator()
        self._network_type = network_type

    def validate(
        self,
        block: Block,
        parent: Optional[Block],
        state: StateManager,
    ) -> ValidationResult:
        """Run all validation checks on a block."""
        checks = [
            self._check_version(block),
            self._check_height(block, parent),
            self._check_parent_hash(block, parent),
            self._check_timestamp(block, parent),
            self._check_gas_limit(block),
            self._check_transactions_root(block),
            self._check_signature(block),
        ]

        for result in checks:
            if not result.valid:
                return result

        # Validate all transactions
        for tx in block.transactions:
            result = self.tx_validator.validate(tx, state, block.height)
            if not result.valid:
                return ValidationResult(
                    valid=False,
                    error=f"Invalid TX {tx.tx_hash_hex[:16]}: {result.error}",
                )

        return ValidationResult(valid=True)

    def _check_version(self, block: Block) -> ValidationResult:
        if block.header.version != BLOCK_HEADER_VERSION:
            return ValidationResult(
                valid=False,
                error=f"Invalid block version: {block.header.version}",
            )
        return ValidationResult(valid=True)

    def _check_height(self, block: Block, parent: Optional[Block]) -> ValidationResult:
        if parent is None:
            if block.height != 0:
                return ValidationResult(valid=False, error="Non-zero genesis height")
        else:
            if block.height != parent.height + 1:
                return ValidationResult(
                    valid=False,
                    error=f"Invalid height: {block.height} (expected {parent.height + 1})",
                )
        return ValidationResult(valid=True)

    def _check_parent_hash(self, block: Block, parent: Optional[Block]) -> ValidationResult:
        if parent is None:
            # Genesis block: verify against hardcoded genesis hash (if set)
            expected = TESTNET_GENESIS_HASH if self._network_type == "testnet" else GENESIS_HASH
            if expected is not None and block.hash != expected:
                return ValidationResult(
                    valid=False,
                    error=f"Genesis hash mismatch: got {block.hash.hex()[:32]}...",
                )
            return ValidationResult(valid=True)
        if block.header.previous_hash != parent.hash:
            return ValidationResult(valid=False, error="Parent hash mismatch")
        return ValidationResult(valid=True)

    def _check_timestamp(self, block: Block, parent: Optional[Block]) -> ValidationResult:
        if parent and block.header.timestamp <= parent.header.timestamp:
            return ValidationResult(valid=False, error="Timestamp not increasing")
        return ValidationResult(valid=True)

    def _check_gas_limit(self, block: Block) -> ValidationResult:
        """
        Dynamic block gas limit validation.
        Gas limit can adjust by at most 1/GAS_LIMIT_ADJUSTMENT_FACTOR per block,
        bounded between MIN_BLOCK_GAS_LIMIT and MAX_BLOCK_GAS_LIMIT.
        This allows the network to scale with demand (like Ethereum EIP-1559).
        """
        if block.header.gas_limit > MAX_BLOCK_GAS_LIMIT:
            return ValidationResult(
                valid=False,
                error=f"Gas limit {block.header.gas_limit} exceeds maximum {MAX_BLOCK_GAS_LIMIT}",
            )
        if block.header.gas_limit < MIN_BLOCK_GAS_LIMIT:
            return ValidationResult(
                valid=False,
                error=f"Gas limit {block.header.gas_limit} below minimum {MIN_BLOCK_GAS_LIMIT}",
            )
        return ValidationResult(valid=True)

    def _check_transactions_root(self, block: Block) -> ValidationResult:
        computed_root = block.compute_transactions_root()
        if block.header.transactions_root != computed_root:
            return ValidationResult(valid=False, error="Transactions root mismatch")
        return ValidationResult(valid=True)

    def _check_signature(self, block: Block) -> ValidationResult:
        if block.height == 0:
            return ValidationResult(valid=True)
        if not block.header.verify_signature():
            return ValidationResult(valid=False, error="Invalid block signature")
        return ValidationResult(valid=True)
