"""
Pre-trained baseline weights for Positronic AI models.

These weights are generated by training on synthetic data to provide
reasonable starting points. They are NOT production-quality and will
be improved through online learning during actual blockchain operation.
"""
import json
import hashlib
import numpy as np
from pathlib import Path
from typing import Dict, Optional


WEIGHTS_DIR = Path(__file__).parent


def get_baseline_weights() -> Dict:
    """Load pre-trained baseline weights.

    Returns a dictionary of model_name -> weight arrays.
    If no pre-trained weights exist, returns Xavier-initialized defaults.
    """
    weights_path = WEIGHTS_DIR / "baseline_weights.json"
    if weights_path.exists():
        with open(weights_path) as f:
            return json.load(f)

    # Generate default Xavier weights
    return _generate_xavier_defaults()


def _generate_xavier_defaults() -> Dict:
    """Generate Xavier-initialized default weights.

    Uses a fixed seed for deterministic cross-node consensus.
    Weight dimensions match the actual model architectures:
    - anomaly_detector: Autoencoder with 35->16->8->4->8->16->35
    - mev_detector: 8-dim input, 4-dim output (lightweight classifier)
    - contract_analyzer: 8-dim input, 4-dim output (lightweight classifier)
    - stability_guardian: 8-dim input, 4-dim output (lightweight classifier)
    """
    np.random.seed(42)

    return {
        "version": 1,
        "anomaly_detector": {
            "encoder_weights": np.random.randn(8, 16).tolist(),
            "encoder_bias": np.zeros(16).tolist(),
            "decoder_weights": np.random.randn(16, 8).tolist(),
            "decoder_bias": np.zeros(8).tolist(),
        },
        "mev_detector": {
            "weights": np.random.randn(8, 4).tolist(),
            "bias": np.zeros(4).tolist(),
        },
        "contract_analyzer": {
            "weights": np.random.randn(8, 4).tolist(),
            "bias": np.zeros(4).tolist(),
        },
        "stability_guardian": {
            "weights": np.random.randn(8, 4).tolist(),
            "bias": np.zeros(4).tolist(),
        },
    }


def save_weights(weights: Dict, filename: str = "baseline_weights.json"):
    """Save weights to the pretrained directory."""
    path = WEIGHTS_DIR / filename
    with open(path, "w") as f:
        json.dump(weights, f, indent=2)
    return path
